name: 'build tools setup action'
inputs:
  os:
    description: 'os'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 'stable'
    - name: Setup cargo-make
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-make
    - name: install dependencies
      shell: bash
      if: inputs.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev librsvg2-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev
