[[dep]]
name = "ab_glyph"
path = "LICENSE"
tag = "ab-glyph-${VERSION}"

[[dep]]
name = "ab_glyph_rasterizer"
path = "LICENSE"
tag = "ab-glyph-rasterizer-${VERSION}"

[[dep]]
name = "ecolor"
path = "LICENSE-MIT"
tag = "${VERSION}"

[[dep]]
name = "egui"
path = "LICENSE-MIT"
tag = "${VERSION}"

[[dep]]
name = "egui-wgpu"
path = "LICENSE-MIT"
tag = "${VERSION}"

[[dep]]
name = "egui-winit"
path = "LICENSE-MIT"
tag = "${VERSION}"

[[dep]]
name = "egui_plot"
path = "LICENSE-MIT"
tag = "${VERSION}"

[[dep]]
name = "emath"
path = "LICENSE-MIT"
tag = "${VERSION}"

[[dep]]
name = "epaint"
path = "LICENSE-MIT"
tag = "${VERSION}"

[[dep]]
name = "libm"
path = "libm/LICENSE.txt"
tag = "libm-v${VERSION}"

[[dep]]
name = "owned_ttf_parser"
path = "LICENSE"
tag = "${VERSION}"

[[dep]]
name = "profiling"
path = "LICENSE-MIT"

[[dep]]
name = "ryu"
path = "LICENSE-APACHE"
tag = "${VERSION}"

[[dep]]
name = "type-map"
path = "LICENSE-MIT"

[[dep]]
name = "windows"
path = "license-mit"

[[dep]]
name = "windows-collections"
path = "license-mit"

[[dep]]
name = "windows-core"
path = "license-mit"

[[dep]]
name = "windows-future"
path = "license-mit"

[[dep]]
name = "windows-implement"
path = "license-mit"

[[dep]]
name = "windows-interface"
path = "license-mit"

[[dep]]
name = "windows-link"
path = "license-mit"

[[dep]]
name = "windows-numerics"
path = "license-mit"

[[dep]]
name = "windows-result"
path = "license-mit"

[[dep]]
name = "windows-strings"
path = "license-mit"

[[dep]]
name = "windows-sys"
path = "license-mit"

[[dep]]
name = "windows-targets"
path = "license-mit"

[[dep]]
name = "windows-threading"
path = "license-mit"

[[dep]]
name = "windows_x86_64_msvc"
path = "license-mit"
